### ISSUE TITLE
PolySpatial dependency

### ISSUE THREAD

**Issue by from2001** [segurvita/PolySpatialEnvironmentDiffuseShader#4]
Could you remove dependency of `"com.unity.polyspatial": "1.1.6"` in package.json?
The package is not available for non-pro users, and error occurs during installation without pro license.

FYI
You could implement features which are only available if PolySpatial installed.
Version defines can be set in assemble definition in your package.

See the example in STYLY-Spatial-Layer-Plugin.
[Packages/com.styly.styly-spatial-layer-plugin/Runtime/com.styly.styly-spatial-layer-plugin.asmdef](https://github.com/styly-dev/STYLY-Spatial-Layer-Plugin/blob/578cfb1894fde76e3b4cdf5c2d74aa76e4e6f81b/Packages/com.styly.styly-spatial-layer-plugin/Runtime/com.styly.styly-spatial-layer-plugin.asmdef#L4)

<img width="604" alt="Screenshot 2024-05-07 at 12 49 30" src="https://github.com/segurvita/PolySpatialEnvironmentDiffuseShader/assets/387880/8007a39f-6544-4e25-81ae-55782cce5503">

**Comment by from2001** [comment]
I see.

I want to add your `PolySpatialEnvironmentDiffuseShader` as a dependency of [VRM_VisualScriptingNodes](https://github.com/from2001/VRM_VisualScriptingNodes).
VRM_VisualScriptingNodes is not PolySpatial dependent, and Shader graph materials are applied only when the build target is visionOS.

Any good idea?

One option is implementing fallback in PolySpatialEnvironmentDiffuseShader if PolySpatial is not installed. So the shader will be compatible even without PolySpatial. What do you think?

**Comment by segurvita** [comment]
Thank you for the advice.

Are you referring to the fallback described in https://docs.unity3d.com/2022.3/Documentation/Manual/SL-Fallback.html ? Unfortunately, ShaderGraph doesn't seem to support fallback functionality.

However, it appears that ShaderGraph does support [Boolean Keywords](https://docs.unity3d.com/Packages/com.unity.shadergraph@10.0/manual/Keywords.html#boolean-keywords), which might allow us to create Shader Variants that support and don't support PolySpatial. I am currently investigating this.

**Comment by segurvita** [comment]
I have removed dependant of PolySpatial using Boolean Keywords of ShaderGraph
